// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package tictacgo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Game struct {
	ID             int64
	FirstPlayer    int64
	SecondPlayer   int64
	CreatingPlayer int64
	BoardState     []byte
	Turn           pgtype.Bool
	UpdatedOn      pgtype.Timestamp
	StartedOn      pgtype.Timestamp
	Result         int32
}

type GameStep struct {
	GameID  int64
	Ord     int32
	MoveRow int32
	MoveCol int32
	Board   []byte
	Turn    pgtype.Bool
}
