// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Game struct {
	ID         int64
	XPlayer    int64
	OPlayer    pgtype.Int8
	BoardState []byte
	XTurn      pgtype.Bool
	UpdatedOn  pgtype.Timestamptz
	StartedOn  pgtype.Timestamptz
	Result     int32
}

type GameStep struct {
	GameID  int64
	Ord     int32
	MoveRow int32
	MoveCol int32
	Board   []byte
	XTurn   bool
	Result  int32
	MadeOn  pgtype.Timestamptz
}

type PlayerAccount struct {
	ID       int64
	Username string
	Passwd   string
	Salt     string
}

type PlayerSession struct {
	Token    string
	PlayerID int64
}
