// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pb/tictacgo.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Cnt           int32                  `protobuf:"varint,3,opt,name=cnt,proto3" json:"cnt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_pb_tictacgo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tictacgo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_pb_tictacgo_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Player) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Player) GetCnt() int32 {
	if x != nil {
		return x.Cnt
	}
	return 0
}

type Players struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*Player              `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Players) Reset() {
	*x = Players{}
	mi := &file_pb_tictacgo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Players) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Players) ProtoMessage() {}

func (x *Players) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tictacgo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Players.ProtoReflect.Descriptor instead.
func (*Players) Descriptor() ([]byte, []int) {
	return file_pb_tictacgo_proto_rawDescGZIP(), []int{1}
}

func (x *Players) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

type Game struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XPlayer       *Player                `protobuf:"bytes,2,opt,name=xPlayer,proto3" json:"xPlayer,omitempty"`
	OPlayer       *Player                `protobuf:"bytes,3,opt,name=oPlayer,proto3" json:"oPlayer,omitempty"`
	BoardState    string                 `protobuf:"bytes,4,opt,name=boardState,proto3" json:"boardState,omitempty"`
	XTurn         bool                   `protobuf:"varint,5,opt,name=xTurn,proto3" json:"xTurn,omitempty"`
	UpdatedOn     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_on,json=updatedOn,proto3" json:"updated_on,omitempty"`
	StartedOn     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_on,json=startedOn,proto3" json:"started_on,omitempty"`
	Result        int32                  `protobuf:"varint,8,opt,name=result,proto3" json:"result,omitempty"`
	Steps         []*Step                `protobuf:"bytes,9,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Game) Reset() {
	*x = Game{}
	mi := &file_pb_tictacgo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tictacgo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_pb_tictacgo_proto_rawDescGZIP(), []int{2}
}

func (x *Game) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Game) GetXPlayer() *Player {
	if x != nil {
		return x.XPlayer
	}
	return nil
}

func (x *Game) GetOPlayer() *Player {
	if x != nil {
		return x.OPlayer
	}
	return nil
}

func (x *Game) GetBoardState() string {
	if x != nil {
		return x.BoardState
	}
	return ""
}

func (x *Game) GetXTurn() bool {
	if x != nil {
		return x.XTurn
	}
	return false
}

func (x *Game) GetUpdatedOn() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedOn
	}
	return nil
}

func (x *Game) GetStartedOn() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedOn
	}
	return nil
}

func (x *Game) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *Game) GetSteps() []*Step {
	if x != nil {
		return x.Steps
	}
	return nil
}

type Games struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Games         []*Game                `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Games) Reset() {
	*x = Games{}
	mi := &file_pb_tictacgo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Games) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Games) ProtoMessage() {}

func (x *Games) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tictacgo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Games.ProtoReflect.Descriptor instead.
func (*Games) Descriptor() ([]byte, []int) {
	return file_pb_tictacgo_proto_rawDescGZIP(), []int{3}
}

func (x *Games) GetGames() []*Game {
	if x != nil {
		return x.Games
	}
	return nil
}

type Step struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        int64                  `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId,omitempty"`
	Ord           int32                  `protobuf:"varint,2,opt,name=ord,proto3" json:"ord,omitempty"`
	MoveRow       int32                  `protobuf:"varint,3,opt,name=moveRow,proto3" json:"moveRow,omitempty"`
	MoveCol       int32                  `protobuf:"varint,4,opt,name=moveCol,proto3" json:"moveCol,omitempty"`
	Board         string                 `protobuf:"bytes,5,opt,name=board,proto3" json:"board,omitempty"`
	XTurn         bool                   `protobuf:"varint,6,opt,name=xTurn,proto3" json:"xTurn,omitempty"`
	Result        int32                  `protobuf:"varint,7,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Step) Reset() {
	*x = Step{}
	mi := &file_pb_tictacgo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Step) ProtoMessage() {}

func (x *Step) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tictacgo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Step.ProtoReflect.Descriptor instead.
func (*Step) Descriptor() ([]byte, []int) {
	return file_pb_tictacgo_proto_rawDescGZIP(), []int{4}
}

func (x *Step) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *Step) GetOrd() int32 {
	if x != nil {
		return x.Ord
	}
	return 0
}

func (x *Step) GetMoveRow() int32 {
	if x != nil {
		return x.MoveRow
	}
	return 0
}

func (x *Step) GetMoveCol() int32 {
	if x != nil {
		return x.MoveCol
	}
	return 0
}

func (x *Step) GetBoard() string {
	if x != nil {
		return x.Board
	}
	return ""
}

func (x *Step) GetXTurn() bool {
	if x != nil {
		return x.XTurn
	}
	return false
}

func (x *Step) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type AuthToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthToken) Reset() {
	*x = AuthToken{}
	mi := &file_pb_tictacgo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthToken) ProtoMessage() {}

func (x *AuthToken) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tictacgo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthToken.ProtoReflect.Descriptor instead.
func (*AuthToken) Descriptor() ([]byte, []int) {
	return file_pb_tictacgo_proto_rawDescGZIP(), []int{5}
}

func (x *AuthToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetGamesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	XPlayer       *Player                `protobuf:"bytes,2,opt,name=xPlayer,proto3" json:"xPlayer,omitempty"`
	OPlayer       *Player                `protobuf:"bytes,3,opt,name=oPlayer,proto3" json:"oPlayer,omitempty"`
	PerPage       int32                  `protobuf:"varint,4,opt,name=perPage,proto3" json:"perPage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGamesReq) Reset() {
	*x = GetGamesReq{}
	mi := &file_pb_tictacgo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGamesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGamesReq) ProtoMessage() {}

func (x *GetGamesReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tictacgo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGamesReq.ProtoReflect.Descriptor instead.
func (*GetGamesReq) Descriptor() ([]byte, []int) {
	return file_pb_tictacgo_proto_rawDescGZIP(), []int{6}
}

func (x *GetGamesReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetGamesReq) GetXPlayer() *Player {
	if x != nil {
		return x.XPlayer
	}
	return nil
}

func (x *GetGamesReq) GetOPlayer() *Player {
	if x != nil {
		return x.OPlayer
	}
	return nil
}

func (x *GetGamesReq) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type GetPlayersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,2,opt,name=perPage,proto3" json:"perPage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayersReq) Reset() {
	*x = GetPlayersReq{}
	mi := &file_pb_tictacgo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayersReq) ProtoMessage() {}

func (x *GetPlayersReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tictacgo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayersReq.ProtoReflect.Descriptor instead.
func (*GetPlayersReq) Descriptor() ([]byte, []int) {
	return file_pb_tictacgo_proto_rawDescGZIP(), []int{7}
}

func (x *GetPlayersReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPlayersReq) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type GetGameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameReq) Reset() {
	*x = GetGameReq{}
	mi := &file_pb_tictacgo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameReq) ProtoMessage() {}

func (x *GetGameReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tictacgo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameReq.ProtoReflect.Descriptor instead.
func (*GetGameReq) Descriptor() ([]byte, []int) {
	return file_pb_tictacgo_proto_rawDescGZIP(), []int{8}
}

func (x *GetGameReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateGameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameReq) Reset() {
	*x = CreateGameReq{}
	mi := &file_pb_tictacgo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameReq) ProtoMessage() {}

func (x *CreateGameReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tictacgo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameReq.ProtoReflect.Descriptor instead.
func (*CreateGameReq) Descriptor() ([]byte, []int) {
	return file_pb_tictacgo_proto_rawDescGZIP(), []int{9}
}

func (x *CreateGameReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type MakeMoveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Row           int32                  `protobuf:"varint,2,opt,name=row,proto3" json:"row,omitempty"`
	Col           int32                  `protobuf:"varint,3,opt,name=col,proto3" json:"col,omitempty"`
	GameId        int64                  `protobuf:"varint,4,opt,name=gameId,proto3" json:"gameId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeMoveReq) Reset() {
	*x = MakeMoveReq{}
	mi := &file_pb_tictacgo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeMoveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeMoveReq) ProtoMessage() {}

func (x *MakeMoveReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tictacgo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeMoveReq.ProtoReflect.Descriptor instead.
func (*MakeMoveReq) Descriptor() ([]byte, []int) {
	return file_pb_tictacgo_proto_rawDescGZIP(), []int{10}
}

func (x *MakeMoveReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *MakeMoveReq) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *MakeMoveReq) GetCol() int32 {
	if x != nil {
		return x.Col
	}
	return 0
}

func (x *MakeMoveReq) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

type CredentialsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialsReq) Reset() {
	*x = CredentialsReq{}
	mi := &file_pb_tictacgo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialsReq) ProtoMessage() {}

func (x *CredentialsReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tictacgo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialsReq.ProtoReflect.Descriptor instead.
func (*CredentialsReq) Descriptor() ([]byte, []int) {
	return file_pb_tictacgo_proto_rawDescGZIP(), []int{11}
}

func (x *CredentialsReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CredentialsReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Player        *Player                `protobuf:"bytes,2,opt,name=Player,proto3" json:"Player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_pb_tictacgo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tictacgo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_pb_tictacgo_proto_rawDescGZIP(), []int{12}
}

func (x *LoginResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResp) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

var File_pb_tictacgo_proto protoreflect.FileDescriptor

const file_pb_tictacgo_proto_rawDesc = "" +
	"\n" +
	"\x11pb/tictacgo.proto\x12\aservice\x1a\x1fgoogle/protobuf/timestamp.proto\"F\n" +
	"\x06Player\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x10\n" +
	"\x03cnt\x18\x03 \x01(\x05R\x03cnt\"4\n" +
	"\aPlayers\x12)\n" +
	"\aplayers\x18\x01 \x03(\v2\x0f.service.PlayerR\aplayers\"\xd5\x02\n" +
	"\x04Game\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12)\n" +
	"\axPlayer\x18\x02 \x01(\v2\x0f.service.PlayerR\axPlayer\x12)\n" +
	"\aoPlayer\x18\x03 \x01(\v2\x0f.service.PlayerR\aoPlayer\x12\x1e\n" +
	"\n" +
	"boardState\x18\x04 \x01(\tR\n" +
	"boardState\x12\x14\n" +
	"\x05xTurn\x18\x05 \x01(\bR\x05xTurn\x129\n" +
	"\n" +
	"updated_on\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedOn\x129\n" +
	"\n" +
	"started_on\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartedOn\x12\x16\n" +
	"\x06result\x18\b \x01(\x05R\x06result\x12#\n" +
	"\x05steps\x18\t \x03(\v2\r.service.StepR\x05steps\",\n" +
	"\x05Games\x12#\n" +
	"\x05games\x18\x01 \x03(\v2\r.service.GameR\x05games\"\xa8\x01\n" +
	"\x04Step\x12\x16\n" +
	"\x06gameId\x18\x01 \x01(\x03R\x06gameId\x12\x10\n" +
	"\x03ord\x18\x02 \x01(\x05R\x03ord\x12\x18\n" +
	"\amoveRow\x18\x03 \x01(\x05R\amoveRow\x12\x18\n" +
	"\amoveCol\x18\x04 \x01(\x05R\amoveCol\x12\x14\n" +
	"\x05board\x18\x05 \x01(\tR\x05board\x12\x14\n" +
	"\x05xTurn\x18\x06 \x01(\bR\x05xTurn\x12\x16\n" +
	"\x06result\x18\a \x01(\x05R\x06result\"!\n" +
	"\tAuthToken\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x91\x01\n" +
	"\vGetGamesReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12)\n" +
	"\axPlayer\x18\x02 \x01(\v2\x0f.service.PlayerR\axPlayer\x12)\n" +
	"\aoPlayer\x18\x03 \x01(\v2\x0f.service.PlayerR\aoPlayer\x12\x18\n" +
	"\aperPage\x18\x04 \x01(\x05R\aperPage\"=\n" +
	"\rGetPlayersReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x18\n" +
	"\aperPage\x18\x02 \x01(\x05R\aperPage\"\x1c\n" +
	"\n" +
	"GetGameReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"%\n" +
	"\rCreateGameReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"_\n" +
	"\vMakeMoveReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x10\n" +
	"\x03row\x18\x02 \x01(\x05R\x03row\x12\x10\n" +
	"\x03col\x18\x03 \x01(\x05R\x03col\x12\x16\n" +
	"\x06gameId\x18\x04 \x01(\x03R\x06gameId\"H\n" +
	"\x0eCredentialsReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"J\n" +
	"\tLoginResp\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12'\n" +
	"\x06Player\x18\x02 \x01(\v2\x0f.service.PlayerR\x06Player2\xf2\x03\n" +
	"\x0fTicTacGoService\x126\n" +
	"\bRegister\x12\x17.service.CredentialsReq\x1a\x0f.service.Player\"\x00\x126\n" +
	"\x05Login\x12\x17.service.CredentialsReq\x1a\x12.service.LoginResp\"\x00\x128\n" +
	"\n" +
	"GetPlayers\x12\x16.service.GetPlayersReq\x1a\x10.service.Players\"\x00\x125\n" +
	"\n" +
	"CreateGame\x12\x16.service.CreateGameReq\x1a\r.service.Game\"\x00\x122\n" +
	"\bGetGames\x12\x14.service.GetGamesReq\x1a\x0e.service.Games\"\x00\x12/\n" +
	"\aGetGame\x12\x13.service.GetGameReq\x1a\r.service.Game\"\x00\x121\n" +
	"\bMakeMove\x12\x14.service.MakeMoveReq\x1a\r.service.Game\"\x00\x125\n" +
	"\vListenSteps\x12\x13.service.GetGameReq\x1a\r.service.Step\"\x000\x01\x12/\n" +
	"\x06WhoAmI\x12\x12.service.AuthToken\x1a\x0f.service.Player\"\x00B\rZ\vTicTacGo/pbb\x06proto3"

var (
	file_pb_tictacgo_proto_rawDescOnce sync.Once
	file_pb_tictacgo_proto_rawDescData []byte
)

func file_pb_tictacgo_proto_rawDescGZIP() []byte {
	file_pb_tictacgo_proto_rawDescOnce.Do(func() {
		file_pb_tictacgo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_tictacgo_proto_rawDesc), len(file_pb_tictacgo_proto_rawDesc)))
	})
	return file_pb_tictacgo_proto_rawDescData
}

var file_pb_tictacgo_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pb_tictacgo_proto_goTypes = []any{
	(*Player)(nil),                // 0: service.Player
	(*Players)(nil),               // 1: service.Players
	(*Game)(nil),                  // 2: service.Game
	(*Games)(nil),                 // 3: service.Games
	(*Step)(nil),                  // 4: service.Step
	(*AuthToken)(nil),             // 5: service.AuthToken
	(*GetGamesReq)(nil),           // 6: service.GetGamesReq
	(*GetPlayersReq)(nil),         // 7: service.GetPlayersReq
	(*GetGameReq)(nil),            // 8: service.GetGameReq
	(*CreateGameReq)(nil),         // 9: service.CreateGameReq
	(*MakeMoveReq)(nil),           // 10: service.MakeMoveReq
	(*CredentialsReq)(nil),        // 11: service.CredentialsReq
	(*LoginResp)(nil),             // 12: service.LoginResp
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
}
var file_pb_tictacgo_proto_depIdxs = []int32{
	0,  // 0: service.Players.players:type_name -> service.Player
	0,  // 1: service.Game.xPlayer:type_name -> service.Player
	0,  // 2: service.Game.oPlayer:type_name -> service.Player
	13, // 3: service.Game.updated_on:type_name -> google.protobuf.Timestamp
	13, // 4: service.Game.started_on:type_name -> google.protobuf.Timestamp
	4,  // 5: service.Game.steps:type_name -> service.Step
	2,  // 6: service.Games.games:type_name -> service.Game
	0,  // 7: service.GetGamesReq.xPlayer:type_name -> service.Player
	0,  // 8: service.GetGamesReq.oPlayer:type_name -> service.Player
	0,  // 9: service.LoginResp.Player:type_name -> service.Player
	11, // 10: service.TicTacGoService.Register:input_type -> service.CredentialsReq
	11, // 11: service.TicTacGoService.Login:input_type -> service.CredentialsReq
	7,  // 12: service.TicTacGoService.GetPlayers:input_type -> service.GetPlayersReq
	9,  // 13: service.TicTacGoService.CreateGame:input_type -> service.CreateGameReq
	6,  // 14: service.TicTacGoService.GetGames:input_type -> service.GetGamesReq
	8,  // 15: service.TicTacGoService.GetGame:input_type -> service.GetGameReq
	10, // 16: service.TicTacGoService.MakeMove:input_type -> service.MakeMoveReq
	8,  // 17: service.TicTacGoService.ListenSteps:input_type -> service.GetGameReq
	5,  // 18: service.TicTacGoService.WhoAmI:input_type -> service.AuthToken
	0,  // 19: service.TicTacGoService.Register:output_type -> service.Player
	12, // 20: service.TicTacGoService.Login:output_type -> service.LoginResp
	1,  // 21: service.TicTacGoService.GetPlayers:output_type -> service.Players
	2,  // 22: service.TicTacGoService.CreateGame:output_type -> service.Game
	3,  // 23: service.TicTacGoService.GetGames:output_type -> service.Games
	2,  // 24: service.TicTacGoService.GetGame:output_type -> service.Game
	2,  // 25: service.TicTacGoService.MakeMove:output_type -> service.Game
	4,  // 26: service.TicTacGoService.ListenSteps:output_type -> service.Step
	0,  // 27: service.TicTacGoService.WhoAmI:output_type -> service.Player
	19, // [19:28] is the sub-list for method output_type
	10, // [10:19] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_pb_tictacgo_proto_init() }
func file_pb_tictacgo_proto_init() {
	if File_pb_tictacgo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_tictacgo_proto_rawDesc), len(file_pb_tictacgo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_tictacgo_proto_goTypes,
		DependencyIndexes: file_pb_tictacgo_proto_depIdxs,
		MessageInfos:      file_pb_tictacgo_proto_msgTypes,
	}.Build()
	File_pb_tictacgo_proto = out.File
	file_pb_tictacgo_proto_goTypes = nil
	file_pb_tictacgo_proto_depIdxs = nil
}
